language: ruby
rvm:
  - 2.1.0
bundler_args: --without development --deployment
cache: bundler
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate --trace
script:
  - bundle exec rspec spec
