default: &default
  adapter: postgresql
  encoding: unicode
  username: md_note_user
  pool: 5

development:
  <<: *default
  database: md_note_development

test:
  <<: *default
  database: md_note_test

production:
  <<: *default
  database: md_note_production
  password: <%= ENV['MD_NOTE_DATABASE_PASSWORD'] %>
